
["Quality Modifiers"]
	UniversalReforgeItem = ["minecraft:diamond", "minecraft:netherite_ingot"]
	DisableRepairingReforging = false
	DisableUniversalReforging = false
	#Disable the universal reforge item for items that have a repair material. (default = false)
	DisableUniversalItemForRepairableItems = false
	#Range: 0 ~ 100
	"Autoforge on first pickup % chance" = 80

